tasks:
  - name: Pull marp-cli image
    init: docker pull marpteam/marp-cli

  - name: Configure command aliases for in container run and exit execution
    command: |
      alias marp='docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG -e MARP_USER="$(id -u):$(id -g)" marpteam/marp-cli'

vscode:
  extensions:
    - marp-team.marp-vscode@1.3.0
